default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres
  host: localhost

development:
  <<: *default
  database: mini_blog_development

test:
  <<: *default
  database: mini_blog_test

production:
  <<: *default
  database: mini_blog_production
  username: mini_blog
  password: <%= ENV["MINI_BLOG_DATABASE_PASSWORD"] %>
